import locale
import sys

def get_system_language():
    try:
        # Get default locale (e.g., ('hu_HU', 'UTF-8'))
        loc = locale.getdefaultlocale()
        if loc and loc[0]:
            return loc[0][:2].lower() # Return 'hu', 'en', 'de', etc.
    except:
        pass
    return "en" # Fallback

TRANSLATIONS = {
    "en": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Studio Quality Downloader & Normalizer",
        "update_btn": "🔄 Update Engine",
        "url_placeholder": "YouTube Video URL...",
        "paste_btn": "PASTE",
        "format_label": "Format:",
        "save_to_btn": "📂 Save to...",
        "quality_label": "Audio Quality:",
        "smart_mode": "Smart Music Mode (Auto-Trim)",
        "playlist_percentage_label": "Playlist %:",
        "download_btn": "DOWNLOAD & CONVERT",
        "open_folder_btn": "📂 Open Folder",
        "error_no_link": "Error: Please provide a link!",
        "start_log": "Starting: {} ({}, {}kbps)",
        "smart_mode_log": "Smart Mode: ON (Auto-Trim & Meta)",
        "download_meta_log": "Downloading and processing Metadata...",
        "download_fail_log": "Failed to download files.",
        "norm_start_log": "{} files downloaded. Starting normalization...",
        "norm_item_log": "[{}/{}] Normalizing: {}",
        "success_log": "ALL PROCESSES FINISHED SUCCESSFULLY!",
        "critical_error": "Critical error: {}",
        "folder_open_error": "Could not open folder: {}",
        "update_start": "Updating engine...",
        "update_success": "Update successful! Please restart the program.",
        "update_error": "Update error: {}",
        "paste_error": "Paste error: {}",
        "download_ready": "Download finished, converting...",
        "save_location": "Save location: {}",
        "folder_create_error": "Error: Folder does not exist and cannot be created.",
        "download_error": "Download error: {}",
        "playlist_detected": "Playlist detected: {}",
        "norm_error": "Normalization error: {}",
        "playlist_items_info": "Playlist items: {}. Downloading: {} ({}%). Starting parallel download...",
        "download_progress": "Downloaded: {}/{}"
    },
    "hu": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Stúdió Minőségű Letöltő & Normalizáló",
        "update_btn": "🔄 Motor Frissítése",
        "url_placeholder": "YouTube Videó Link...",
        "paste_btn": "BEILLESZTÉS",
        "format_label": "Formátum:",
        "save_to_btn": "📂 Mentés ide...",
        "quality_label": "Hangminőség:",
        "smart_mode": "Okos Mód (Auto-Vágás)",
        "playlist_percentage_label": "Lejátszási lista %:",
        "download_btn": "LETÖLTÉS ÉS KONVERTÁLÁS",
        "open_folder_btn": "📂 Mappa Megnyitása",
        "error_no_link": "Hiba: Kérlek adj meg egy linket!",
        "start_log": "Indítás: {} ({}, {}kbps)",
        "smart_mode_log": "Okos Mód: BE (Auto-Vágás & Meta)",
        "download_meta_log": "Letöltés és Metadata feldolgozás...",
        "download_fail_log": "Nem sikerült fájlokat letölteni.",
        "norm_start_log": "{} fájl letöltve. Normalizálás indítása...",
        "norm_item_log": "[{}/{}] Normalizálás: {}",
        "success_log": "MINDEN FOLYAMAT SIKERESEN BEFEJEZŐDÖTT!",
        "critical_error": "Kritikus hiba: {}",
        "folder_open_error": "Nem sikerült megnyitni a mappát: {}",
        "update_start": "Motor frissítése folyamatban...",
        "update_success": "Sikeres frissítés! Kérlek indítsd újra a programot.",
        "update_error": "Hiba a frissítésnél: {}",
        "paste_error": "Hiba a beillesztésnél: {}",
        "download_ready": "Letöltés kész, konvertálás...",
        "save_location": "Mentés helye: {}",
        "folder_create_error": "Hiba: A mappa nem létezik és nem hozható létre.",
        "download_error": "Letöltési hiba: {}",
        "playlist_detected": "Lejátszási lista észlelve: {}",
        "norm_error": "Normalizálási hiba: {}",
        "playlist_items_info": "Playlist elemek száma: {}. Letöltendő: {} ({}%). Párhuzamos letöltés indítása...",
        "download_progress": "Letöltve: {}/{}"
    },
    "de": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Studio-Qualität Downloader & Normalizer",
        "update_btn": "🔄 Engine Aktualisieren",
        "url_placeholder": "YouTube Video URL...",
        "paste_btn": "EINFÜGEN",
        "format_label": "Format:",
        "save_to_btn": "📂 Speichern unter...",
        "quality_label": "Audioqualität:",
        "smart_mode": "Smart-Modus (Auto-Trim)",
        "playlist_percentage_label": "Wiedergabeliste %:",
        "download_btn": "HERUNTERLADEN & KONVERTIEREN",
        "open_folder_btn": "📂 Ordner Öffnen",
        "error_no_link": "Fehler: Bitte geben Sie einen Link ein!",
        "start_log": "Starten: {} ({}, {}kbps)",
        "smart_mode_log": "Smart-Modus: EIN (Auto-Trim & Meta)",
        "download_meta_log": "Herunterladen und Metadaten verarbeiten...",
        "download_fail_log": "Dateien konnten nicht heruntergeladen werden.",
        "norm_start_log": "{} Dateien heruntergeladen. Starte Normalisierung...",
        "norm_item_log": "[{}/{}] Normalisierung: {}",
        "success_log": "ALLE PROZESSE ERFOLGREICH ABGESCHLOSSEN!",
        "critical_error": "Kritischer Fehler: {}",
        "folder_open_error": "Ordner konnte nicht geöffnet werden: {}",
        "update_start": "Engine wird aktualisiert...",
        "update_success": "Update erfolgreich! Bitte starten Sie das Programm neu.",
        "update_error": "Update-Fehler: {}",
        "paste_error": "Fehler beim Einfügen: {}",
        "download_ready": "Download fertig, konvertiere...",
        "save_location": "Speicherort: {}",
        "folder_create_error": "Fehler: Ordner existiert nicht und kann nicht erstellt werden.",
        "download_error": "Download-Fehler: {}",
        "playlist_detected": "Wiedergabeliste erkannt: {}",
        "norm_error": "Normalisierungsfehler: {}",
        "playlist_items_info": "Wiedergabeliste Elemente: {}. Herunterladen: {} ({}%). Starte parallelen Download...",
        "download_progress": "Heruntergeladen: {}/{}"
    },
    "ru": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Загрузчик и нормализатор студийного качества",
        "update_btn": "🔄 Обновить движок",
        "url_placeholder": "Ссылка на видео YouTube...",
        "paste_btn": "ВСТАВИТЬ",
        "format_label": "Формат:",
        "save_to_btn": "📂 Сохранить в...",
        "quality_label": "Качество аудио:",
        "smart_mode": "Умный режим (Авто-обрезка)",
        "playlist_percentage_label": "Плейлист %:",
        "download_btn": "СКАЧАТЬ И КОНВЕРТИРОВАТЬ",
        "open_folder_btn": "📂 Открыть папку",
        "error_no_link": "Ошибка: Пожалуйста, укажите ссылку!",
        "start_log": "Запуск: {} ({}, {}kbps)",
        "smart_mode_log": "Умный режим: ВКЛ (Авто-обрезка и мета)",
        "download_meta_log": "Загрузка и обработка метаданных...",
        "download_fail_log": "Не удалось скачать файлы.",
        "norm_start_log": "{} файлов скачано. Запуск нормализации...",
        "norm_item_log": "[{}/{}] Нормализация: {}",
        "success_log": "ВСЕ ПРОЦЕССЫ УСПЕШНО ЗАВЕРШЕНЫ!",
        "critical_error": "Критическая ошибка: {}",
        "folder_open_error": "Не удалось открыть папку: {}",
        "update_start": "Обновление движка...",
        "update_success": "Обновление успешно! Пожалуйста, перезапустите программу.",
        "update_error": "Ошибка обновления: {}",
        "paste_error": "Ошибка вставки: {}",
        "download_ready": "Загрузка завершена, конвертация...",
        "save_location": "Место сохранения: {}",
        "folder_create_error": "Ошибка: Папка не существует и не может быть создана.",
        "download_error": "Ошибка загрузки: {}",
        "playlist_detected": "Обнаружен плейлист: {}",
        "norm_error": "Ошибка нормализации: {}",
        "playlist_items_info": "Элементов плейлиста: {}. Загрузка: {} ({}%). Запуск параллельной загрузки...",
        "download_progress": "Загружено: {}/{}"
    },
    "sv": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Nedladdare och Normaliserare i Studiokvalitet",
        "update_btn": "🔄 Uppdatera Motor",
        "url_placeholder": "YouTube Video URL...",
        "paste_btn": "KLISTRA IN",
        "format_label": "Format:",
        "save_to_btn": "📂 Spara till...",
        "quality_label": "Ljudkvalitet:",
        "smart_mode": "Smart Läge (Auto-Trim)",
        "playlist_percentage_label": "Spellista %:",
        "download_btn": "LADDA NER & KONVERTERA",
        "open_folder_btn": "📂 Öppna Mapp",
        "error_no_link": "Fel: Vänligen ange en länk!",
        "start_log": "Startar: {} ({}, {}kbps)",
        "smart_mode_log": "Smart Läge: PÅ (Auto-Trim & Meta)",
        "download_meta_log": "Laddar ner och bearbetar metadata...",
        "download_fail_log": "Misslyckades med att ladda ner filer.",
        "norm_start_log": "{} filer nedladdade. Startar normalisering...",
        "norm_item_log": "[{}/{}] Normaliserar: {}",
        "success_log": "ALLA PROCESSER SLUTFÖRDA!",
        "critical_error": "Kritiskt fel: {}",
        "folder_open_error": "Kunde inte öppna mapp: {}",
        "update_start": "Uppdaterar motor...",
        "update_success": "Uppdatering lyckades! Vänligen starta om programmet.",
        "update_error": "Uppdateringsfel: {}",
        "paste_error": "Inklistringsfel: {}",
        "download_ready": "Nedladdning klar, konverterar...",
        "save_location": "Sparplats: {}",
        "folder_create_error": "Fel: Mappen finns inte och kan inte skapas.",
        "download_error": "Nedladdningsfel: {}",
        "playlist_detected": "Spellista upptäckt: {}",
        "norm_error": "Normaliseringsfel: {}",
        "playlist_items_info": "Spellista objekt: {}. Nedladdning: {} ({}%). Startar parallell nedladdning...",
        "download_progress": "Nedladdat: {}/{}"
    },
    "no": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Nedlaster og Normaliserer i Studiokvalitet",
        "update_btn": "🔄 Oppdater Motor",
        "url_placeholder": "YouTube Video URL...",
        "paste_btn": "LIM INN",
        "format_label": "Format:",
        "save_to_btn": "📂 Lagre til...",
        "quality_label": "Lydkvalitet:",
        "smart_mode": "Smart Modus (Auto-Trim)",
        "playlist_percentage_label": "Spilleliste %:",
        "download_btn": "LAST NED & KONVERTER",
        "open_folder_btn": "📂 Åpne Mappe",
        "error_no_link": "Feil: Vennligst oppgi en lenke!",
        "start_log": "Starter: {} ({}, {}kbps)",
        "smart_mode_log": "Smart Modus: PÅ (Auto-Trim & Meta)",
        "download_meta_log": "Laster ned og behandler metadata...",
        "download_fail_log": "Kunne ikke laste ned filer.",
        "norm_start_log": "{} filer lastet ned. Starter normalisering...",
        "norm_item_log": "[{}/{}] Normaliserer: {}",
        "success_log": "ALLE PROSESSER FULLFØRT!",
        "critical_error": "Kritisk feil: {}",
        "folder_open_error": "Kunne ikke åpne mappe: {}",
        "update_start": "Oppdaterer motor...",
        "update_success": "Oppdatering vellykket! Vennligst start programmet på nytt.",
        "update_error": "Oppdateringsfeil: {}",
        "paste_error": "Innlimingsfeil: {}",
        "download_ready": "Nedlasting ferdig, konverterer...",
        "save_location": "Lagringssted: {}",
        "folder_create_error": "Feil: Mappen finnes ikke og kan ikke opprettes.",
        "download_error": "Nedlastingsfeil: {}",
        "playlist_detected": "Spilleliste oppdaget: {}",
        "norm_error": "Normaliseringsfeil: {}",
        "playlist_items_info": "Spilleliste elementer: {}. Laster ned: {} ({}%). Starter parallell nedlasting...",
        "download_progress": "Nedlastet: {}/{}"
    },
    "it": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Downloader e Normalizzatore di Qualità Studio",
        "update_btn": "🔄 Aggiorna Motore",
        "url_placeholder": "URL Video YouTube...",
        "paste_btn": "INCOLLA",
        "format_label": "Formato:",
        "save_to_btn": "📂 Salva in...",
        "quality_label": "Qualità Audio:",
        "smart_mode": "Modalità Smart (Auto-Trim)",
        "playlist_percentage_label": "Playlist %:",
        "download_btn": "SCARICA E CONVERTI",
        "open_folder_btn": "📂 Apri Cartella",
        "error_no_link": "Errore: Inserisci un link!",
        "start_log": "Avvio: {} ({}, {}kbps)",
        "smart_mode_log": "Modalità Smart: ON (Auto-Trim & Meta)",
        "download_meta_log": "Download ed elaborazione metadati...",
        "download_fail_log": "Impossibile scaricare i file.",
        "norm_start_log": "{} file scaricati. Avvio normalizzazione...",
        "norm_item_log": "[{}/{}] Normalizzazione: {}",
        "success_log": "TUTTI I PROCESSI COMPLETATI CON SUCCESSO!",
        "critical_error": "Errore critico: {}",
        "folder_open_error": "Impossibile aprire la cartella: {}",
        "update_start": "Aggiornamento motore...",
        "update_success": "Aggiornamento riuscito! Riavvia il programma.",
        "update_error": "Errore aggiornamento: {}",
        "paste_error": "Errore incolla: {}",
        "download_ready": "Download completato, conversione...",
        "save_location": "Posizione salvataggio: {}",
        "folder_create_error": "Errore: La cartella non esiste e non può essere creata.",
        "download_error": "Errore di download: {}",
        "playlist_detected": "Playlist rilevata: {}",
        "norm_error": "Errore di normalizzazione: {}",
        "playlist_items_info": "Elementi playlist: {}. Download: {} ({}%). Avvio download parallelo...",
        "download_progress": "Scaricati: {}/{}"
    },
    "es": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Descargador y Normalizador de Calidad de Estudio",
        "update_btn": "🔄 Actualizar Motor",
        "url_placeholder": "URL del Video de YouTube...",
        "paste_btn": "PEGAR",
        "format_label": "Formato:",
        "save_to_btn": "📂 Guardar en...",
        "quality_label": "Calidad de Audio:",
        "smart_mode": "Modo Inteligente (Auto-Recorte)",
        "playlist_percentage_label": "Lista %:",
        "download_btn": "DESCARGAR Y CONVERTIR",
        "open_folder_btn": "📂 Abrir Carpeta",
        "error_no_link": "Error: ¡Por favor ingrese un enlace!",
        "start_log": "Iniciando: {} ({}, {}kbps)",
        "smart_mode_log": "Modo Inteligente: ENCENDIDO (Auto-Recorte y Meta)",
        "download_meta_log": "Descargando y procesando metadatos...",
        "download_fail_log": "No se pudieron descargar los archivos.",
        "norm_start_log": "{} archivos descargados. Iniciando normalización...",
        "norm_item_log": "[{}/{}] Normalizando: {}",
        "success_log": "¡TODOS LOS PROCESOS FINALIZADOS CON ÉXITO!",
        "critical_error": "Error crítico: {}",
        "folder_open_error": "No se pudo abrir la carpeta: {}",
        "update_start": "Actualizando motor...",
        "update_success": "¡Actualización exitosa! Por favor reinicie el programa.",
        "update_error": "Error de actualización: {}",
        "paste_error": "Error al pegar: {}",
        "download_ready": "Descarga terminada, convirtiendo...",
        "save_location": "Ubicación de guardado: {}",
        "folder_create_error": "Error: La carpeta no existe y no se puede crear.",
        "download_error": "Error de descarga: {}",
        "playlist_detected": "Lista de reproducción detectada: {}",
        "norm_error": "Error de normalización: {}",
        "playlist_items_info": "Elementos de lista: {}. Descargando: {} ({}%). Iniciando descarga paralela...",
        "download_progress": "Descargado: {}/{}"
    },
    "fr": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Téléchargeur et Normalisateur de Qualité Studio",
        "update_btn": "🔄 Mettre à jour le moteur",
        "url_placeholder": "URL de la vidéo YouTube...",
        "paste_btn": "COLLER",
        "format_label": "Format:",
        "save_to_btn": "📂 Enregistrer sous...",
        "quality_label": "Qualité Audio:",
        "smart_mode": "Mode Intelligent (Auto-Trim)",
        "playlist_percentage_label": "Playlist %:",
        "download_btn": "TÉLÉCHARGER ET CONVERTIR",
        "open_folder_btn": "📂 Ouvrir le dossier",
        "error_no_link": "Erreur : Veuillez fournir un lien !",
        "start_log": "Démarrage : {} ({}, {}kbps)",
        "smart_mode_log": "Mode Intelligent : ACTIVÉ (Auto-Trim & Meta)",
        "download_meta_log": "Téléchargement et traitement des métadonnées...",
        "download_fail_log": "Échec du téléchargement des fichiers.",
        "norm_start_log": "{} fichiers téléchargés. Démarrage de la normalisation...",
        "norm_item_log": "[{}/{}] Normalisation : {}",
        "success_log": "TOUS LES PROCESSUS TERMINÉS AVEC SUCCÈS !",
        "critical_error": "Erreur critique : {}",
        "folder_open_error": "Impossible d'ouvrir le dossier : {}",
        "update_start": "Mise à jour du moteur...",
        "update_success": "Mise à jour réussie ! Veuillez redémarrer le programme.",
        "update_error": "Erreur de mise à jour : {}",
        "paste_error": "Erreur de collage : {}",
        "download_ready": "Téléchargement terminé, conversion...",
        "save_location": "Emplacement de sauvegarde : {}",
        "folder_create_error": "Erreur : Le dossier n'existe pas et ne peut pas être créé.",
        "download_error": "Erreur de téléchargement : {}",
        "playlist_detected": "Playlist détectée : {}",
        "norm_error": "Erreur de normalisation : {}",
        "playlist_items_info": "Éléments de playlist : {}. Téléchargement : {} ({}%). Démarrage du téléchargement parallèle...",
        "download_progress": "Téléchargé : {}/{}"
    },
    "sk": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Sťahovač a Normalizér Štúdiovej Kvality",
        "update_btn": "🔄 Aktualizovať Motor",
        "url_placeholder": "URL YouTube Videa...",
        "paste_btn": "VLOŽIŤ",
        "format_label": "Formát:",
        "save_to_btn": "📂 Uložiť do...",
        "quality_label": "Kvalita Zvuku:",
        "smart_mode": "Inteligentný Režim (Auto-Orezanie)",
        "playlist_percentage_label": "Playlist %:",
        "download_btn": "STIAHNUŤ A KONVERTOVAŤ",
        "open_folder_btn": "📂 Otvoriť Priečinok",
        "error_no_link": "Chyba: Zadajte odkaz!",
        "start_log": "Spúšťanie: {} ({}, {}kbps)",
        "smart_mode_log": "Inteligentný Režim: ZAP (Auto-Orezanie & Meta)",
        "download_meta_log": "Sťahovanie a spracovanie metadát...",
        "download_fail_log": "Nepodarilo sa stiahnuť súbory.",
        "norm_start_log": "{} súborov stiahnutých. Spúšťanie normalizácie...",
        "norm_item_log": "[{}/{}] Normalizácia: {}",
        "success_log": "VŠETKY PROCESY ÚSPEŠNE DOKONČENÉ!",
        "critical_error": "Kritická chyba: {}",
        "folder_open_error": "Nepodarilo sa otvoriť priečinok: {}",
        "update_start": "Aktualizácia motora...",
        "update_success": "Aktualizácia úspešná! Reštartujte program.",
        "update_error": "Chyba aktualizácie: {}",
        "paste_error": "Chyba vloženia: {}",
        "download_ready": "Sťahovanie dokončené, konverzia...",
        "save_location": "Miesto uloženia: {}",
        "folder_create_error": "Chyba: Priečinok neexistuje a nedá sa vytvoriť.",
        "download_error": "Chyba sťahovania: {}",
        "playlist_detected": "Zistený zoznam skladieb: {}",
        "norm_error": "Chyba normalizácie: {}",
        "playlist_items_info": "Položky playlistu: {}. Sťahovanie: {} ({}%). Spúšťanie paralelného sťahovania...",
        "download_progress": "Stiahnuté: {}/{}"
    },
    "ro": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Descărcător și Normalizator de Calitate Studio",
        "update_btn": "🔄 Actualizare Motor",
        "url_placeholder": "URL Video YouTube...",
        "paste_btn": "LIPEȘTE",
        "format_label": "Format:",
        "save_to_btn": "📂 Salvează în...",
        "quality_label": "Calitate Audio:",
        "smart_mode": "Mod Inteligent (Auto-Trim)",
        "playlist_percentage_label": "Playlist %:",
        "download_btn": "DESCARCĂ ȘI CONVERTEȘTE",
        "open_folder_btn": "📂 Deschide Dosar",
        "error_no_link": "Eroare: Vă rugăm să introduceți un link!",
        "start_log": "Pornire: {} ({}, {}kbps)",
        "smart_mode_log": "Mod Inteligent: PORNIT (Auto-Trim & Meta)",
        "download_meta_log": "Descărcare și procesare metadate...",
        "download_fail_log": "Nu s-au putut descărca fișierele.",
        "norm_start_log": "{} fișiere descărcate. Începere normalizare...",
        "norm_item_log": "[{}/{}] Normalizare: {}",
        "success_log": "TOATE PROCESELE FINALIZATE CU SUCCES!",
        "critical_error": "Eroare critică: {}",
        "folder_open_error": "Nu s-a putut deschide dosarul: {}",
        "update_start": "Actualizare motor...",
        "update_success": "Actualizare reușită! Vă rugăm să reporniți programul.",
        "update_error": "Eroare actualizare: {}",
        "paste_error": "Eroare lipire: {}",
        "download_ready": "Descărcare finalizată, conversie...",
        "save_location": "Locație salvare: {}",
        "folder_create_error": "Eroare: Dosarul nu există și nu poate fi creat.",
        "download_error": "Eroare de descărcare: {}",
        "playlist_detected": "Playlist detectat: {}",
        "norm_error": "Eroare de normalizare: {}",
        "playlist_items_info": "Elemente playlist: {}. Descărcare: {} ({}%). Începere descărcare paralelă...",
        "download_progress": "Descărcat: {}/{}"
    },
    "hr": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Preuzimatelj i Normalizator Studijske Kvalitete",
        "update_btn": "🔄 Ažuriraj Motor",
        "url_placeholder": "YouTube Video URL...",
        "paste_btn": "ZALIJEPI",
        "format_label": "Format:",
        "save_to_btn": "📂 Spremi u...",
        "quality_label": "Kvaliteta Zvuka:",
        "smart_mode": "Pametni Način (Auto-Rezanje)",
        "playlist_percentage_label": "Popis %:",
        "download_btn": "PREUZMI I PRETVORI",
        "open_folder_btn": "📂 Otvori Mapu",
        "error_no_link": "Greška: Molimo unesite poveznicu!",
        "start_log": "Pokretanje: {} ({}, {}kbps)",
        "smart_mode_log": "Pametni Način: UKLJUČENO (Auto-Rezanje & Meta)",
        "download_meta_log": "Preuzimanje i obrada metapodataka...",
        "download_fail_log": "Nije uspjelo preuzimanje datoteka.",
        "norm_start_log": "{} datoteka preuzeto. Pokretanje normalizacije...",
        "norm_item_log": "[{}/{}] Normalizacija: {}",
        "success_log": "SVI PROCESI USPJEŠNO ZAVRŠENI!",
        "critical_error": "Kritična greška: {}",
        "folder_open_error": "Nije moguće otvoriti mapu: {}",
        "update_start": "Ažuriranje motora...",
        "update_success": "Ažuriranje uspješno! Molimo ponovno pokrenite program.",
        "update_error": "Greška ažuriranja: {}",
        "paste_error": "Greška lijepljenja: {}",
        "download_ready": "Preuzimanje završeno, pretvaranje...",
        "save_location": "Mjesto spremanja: {}",
        "folder_create_error": "Greška: Mapa ne postoji i ne može se stvoriti.",
        "download_error": "Greška pri preuzimanju: {}",
        "playlist_detected": "Otkriven popis za reprodukciju: {}",
        "norm_error": "Greška normalizacije: {}",
        "playlist_items_info": "Stavki popisa: {}. Preuzimanje: {} ({}%). Pokretanje paralelnog preuzimanja...",
        "download_progress": "Preuzeto: {}/{}"
    },
    "tr": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Stüdyo Kalitesinde İndirici ve Normalleştirici",
        "update_btn": "🔄 Motoru Güncelle",
        "url_placeholder": "YouTube Video URL...",
        "paste_btn": "YAPIŞTIR",
        "format_label": "Format:",
        "save_to_btn": "📂 Şuraya Kaydet...",
        "quality_label": "Ses Kalitesi:",
        "smart_mode": "Akıllı Mod (Otomatik Kırpma)",
        "playlist_percentage_label": "Çalma listesi %:",
        "download_btn": "İNDİR VE DÖNÜŞTÜR",
        "open_folder_btn": "📂 Klasörü Aç",
        "error_no_link": "Hata: Lütfen bir bağlantı girin!",
        "start_log": "Başlatılıyor: {} ({}, {}kbps)",
        "smart_mode_log": "Akıllı Mod: AÇIK (Otomatik Kırpma & Meta)",
        "download_meta_log": "Meta veriler indiriliyor ve işleniyor...",
        "download_fail_log": "Dosyalar indirilemedi.",
        "norm_start_log": "{} dosya indirildi. Normalleştirme başlatılıyor...",
        "norm_item_log": "[{}/{}] Normalleştirme: {}",
        "success_log": "TÜM İŞLEMLER BAŞARIYLA TAMAMLANDI!",
        "critical_error": "Kritik hata: {}",
        "folder_open_error": "Klasör açılamadı: {}",
        "update_start": "Motor güncelleniyor...",
        "update_success": "Güncelleme başarılı! Lütfen programı yeniden başlatın.",
        "update_error": "Güncelleme hatası: {}",
        "paste_error": "Yapıştırma hatası: {}",
        "download_ready": "İndirme tamamlandı, dönüştürülüyor...",
        "save_location": "Kayıt yeri: {}",
        "folder_create_error": "Hata: Klasör mevcut değil ve oluşturulamıyor.",
        "download_error": "İndirme hatası: {}",
        "playlist_detected": "Oynatma listesi algılandı: {}",
        "norm_error": "Normalleştirme hatası: {}",
        "playlist_items_info": "Çalma listesi öğeleri: {}. İndiriliyor: {} ({}%). Paralel indirme başlatılıyor...",
        "download_progress": "İndirildi: {}/{}"
    },
    "el": {
        "title": "YT Audio Converter Pro",
        "subtitle": "Λήψη και Κανονικοποίηση Ποιότητας Στούντιο",
        "update_btn": "🔄 Ενημέρωση Μηχανής",
        "url_placeholder": "URL Βίντεο YouTube...",
        "paste_btn": "ΕΠΙΚΟΛΛΗΣΗ",
        "format_label": "Μορφή:",
        "save_to_btn": "📂 Αποθήκευση σε...",
        "quality_label": "Ποιότητα Ήχου:",
        "smart_mode": "Έξυπνη Λειτουργία (Αυτόματη Περικοπή)",
        "playlist_percentage_label": "Λίστα %:",
        "download_btn": "ΛΗΨΗ ΚΑΙ ΜΕΤΑΤΡΟΠΗ",
        "open_folder_btn": "📂 Άνοιγμα Φακέλου",
        "error_no_link": "Σφάλμα: Παρακαλώ εισάγετε έναν σύνδεσμο!",
        "start_log": "Έναρξη: {} ({}, {}kbps)",
        "smart_mode_log": "Έξυπνη Λειτουργία: ΕΝΕΡΓΗ (Αυτόματη Περικοπή & Meta)",
        "download_meta_log": "Λήψη και επεξεργασία μεταδεδομένων...",
        "download_fail_log": "Αποτυχία λήψης αρχείων.",
        "norm_start_log": "{} αρχεία λήφθηκαν. Έναρξη κανονικοποίησης...",
        "norm_item_log": "[{}/{}] Κανονικοποίηση: {}",
        "success_log": "ΟΛΕΣ ΟΙ ΔΙΑΔΙΚΑΣΙΕΣ ΟΛΟΚΛΗΡΩΘΗΚΑΝ ΕΠΙΤΥΧΩΣ!",
        "critical_error": "Κρίσιμο σφάλμα: {}",
        "folder_open_error": "Αδυναμία ανοίγματος φακέλου: {}",
        "update_start": "Ενημέρωση μηχανής...",
        "update_success": "Η ενημέρωση ήταν επιτυχής! Παρακαλώ επανεκκινήστε το πρόγραμμα.",
        "update_error": "Σφάλμα ενημέρωσης: {}",
        "paste_error": "Σφάλμα επικόλλησης: {}",
        "download_ready": "Η λήψη ολοκληρώθηκε, μετατροπή...",
        "save_location": "Τοποθεσία αποθήκευσης: {}",
        "folder_create_error": "Σφάλμα: Ο φάκελος δεν υπάρχει και δεν μπορεί να δημιουργηθεί.",
        "download_error": "Σφάλμα λήψης: {}",
        "playlist_detected": "Εντοπίστηκε λίστα αναπαραγωγής: {}",
        "norm_error": "Σφάλμα κανονικοποίησης: {}",
        "playlist_items_info": "Στοιχεία λίστας: {}. Λήψη: {} ({}%). Έναρξη παράλληλης λήψης...",
        "download_progress": "Λήφθηκε: {}/{}"
    }
}
